/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoracastro;

/**
 *
 * @author Thales
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDisplay = new javax.swing.JLabel();
        jBClear = new javax.swing.JButton();
        jBSin = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBCos = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jBBinDec = new javax.swing.JButton();
        jBTan = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jBPoint = new javax.swing.JButton();
        jBBinHex = new javax.swing.JButton();
        jBBinOct = new javax.swing.JButton();
        jBDivision = new javax.swing.JButton();
        jBTimes = new javax.swing.JButton();
        jBMinus = new javax.swing.JButton();
        jBSquareRoot = new javax.swing.JButton();
        jBPercentage = new javax.swing.JButton();
        jBReverse = new javax.swing.JButton();
        jBEquals = new javax.swing.JButton();
        jBOpposite = new javax.swing.JButton();
        jBPlus = new javax.swing.JButton();
        jBOctDec = new javax.swing.JButton();
        jBCubeRoot = new javax.swing.JButton();
        jBPower = new javax.swing.JButton();
        jBAbsolute = new javax.swing.JButton();
        jBLog = new javax.swing.JButton();
        jBFactorial = new javax.swing.JButton();
        jBDecBin = new javax.swing.JButton();
        jBOctBin = new javax.swing.JButton();
        jBOctHex = new javax.swing.JButton();
        jBHexOct = new javax.swing.JButton();
        jBDecHex = new javax.swing.JButton();
        jBDecOct = new javax.swing.JButton();
        jBHexDec = new javax.swing.JButton();
        jBHexBin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLDisplay.setBackground(new java.awt.Color(0, 0, 0));
        jLDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLDisplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jBClear.setBackground(new java.awt.Color(255, 255, 255));
        jBClear.setText("Limpar");
        jBClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClearActionPerformed(evt);
            }
        });

        jBSin.setBackground(new java.awt.Color(204, 204, 255));
        jBSin.setText("sen");
        jBSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSinActionPerformed(evt);
            }
        });

        jB7.setBackground(new java.awt.Color(255, 204, 204));
        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB4.setBackground(new java.awt.Color(255, 204, 204));
        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB1.setBackground(new java.awt.Color(255, 204, 204));
        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB0.setBackground(new java.awt.Color(255, 204, 204));
        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jBCos.setBackground(new java.awt.Color(204, 204, 255));
        jBCos.setText("cos");
        jBCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCosActionPerformed(evt);
            }
        });

        jB8.setBackground(new java.awt.Color(255, 204, 204));
        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB5.setBackground(new java.awt.Color(255, 204, 204));
        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB2.setBackground(new java.awt.Color(255, 204, 204));
        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jBBinDec.setBackground(new java.awt.Color(255, 255, 204));
        jBBinDec.setText("BD");
        jBBinDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBinDecActionPerformed(evt);
            }
        });

        jBTan.setBackground(new java.awt.Color(204, 204, 255));
        jBTan.setText("tan");
        jBTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTanActionPerformed(evt);
            }
        });

        jB9.setBackground(new java.awt.Color(255, 204, 204));
        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB6.setBackground(new java.awt.Color(255, 204, 204));
        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB3.setBackground(new java.awt.Color(255, 204, 204));
        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jBPoint.setBackground(new java.awt.Color(255, 255, 255));
        jBPoint.setText(".");
        jBPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPointActionPerformed(evt);
            }
        });

        jBBinHex.setBackground(new java.awt.Color(255, 255, 204));
        jBBinHex.setText("BH");
        jBBinHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBinHexActionPerformed(evt);
            }
        });

        jBBinOct.setBackground(new java.awt.Color(255, 255, 204));
        jBBinOct.setText("BO");
        jBBinOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBinOctActionPerformed(evt);
            }
        });

        jBDivision.setBackground(new java.awt.Color(204, 255, 204));
        jBDivision.setText("/");
        jBDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivisionActionPerformed(evt);
            }
        });

        jBTimes.setBackground(new java.awt.Color(204, 255, 204));
        jBTimes.setText("*");
        jBTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTimesActionPerformed(evt);
            }
        });

        jBMinus.setBackground(new java.awt.Color(204, 255, 204));
        jBMinus.setText("-");
        jBMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinusActionPerformed(evt);
            }
        });

        jBSquareRoot.setBackground(new java.awt.Color(204, 204, 255));
        jBSquareRoot.setText("√");
        jBSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSquareRootActionPerformed(evt);
            }
        });

        jBPercentage.setBackground(new java.awt.Color(204, 204, 255));
        jBPercentage.setText("%");
        jBPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPercentageActionPerformed(evt);
            }
        });

        jBReverse.setBackground(new java.awt.Color(204, 204, 255));
        jBReverse.setText("1/x");
        jBReverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReverseActionPerformed(evt);
            }
        });

        jBEquals.setBackground(new java.awt.Color(255, 255, 255));
        jBEquals.setText("=");
        jBEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEqualsActionPerformed(evt);
            }
        });

        jBOpposite.setBackground(new java.awt.Color(204, 204, 255));
        jBOpposite.setText("+-");
        jBOpposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOppositeActionPerformed(evt);
            }
        });

        jBPlus.setBackground(new java.awt.Color(204, 255, 204));
        jBPlus.setText("+");
        jBPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlusActionPerformed(evt);
            }
        });

        jBOctDec.setBackground(new java.awt.Color(255, 255, 204));
        jBOctDec.setText("OD");
        jBOctDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOctDecActionPerformed(evt);
            }
        });

        jBCubeRoot.setBackground(new java.awt.Color(204, 204, 255));
        jBCubeRoot.setText("³√");
        jBCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCubeRootActionPerformed(evt);
            }
        });

        jBPower.setBackground(new java.awt.Color(204, 204, 255));
        jBPower.setText("pot");
        jBPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPowerActionPerformed(evt);
            }
        });

        jBAbsolute.setBackground(new java.awt.Color(204, 204, 255));
        jBAbsolute.setText("abs");
        jBAbsolute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbsoluteActionPerformed(evt);
            }
        });

        jBLog.setBackground(new java.awt.Color(204, 204, 255));
        jBLog.setText("log");
        jBLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogActionPerformed(evt);
            }
        });

        jBFactorial.setBackground(new java.awt.Color(204, 204, 255));
        jBFactorial.setText("n!");
        jBFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFactorialActionPerformed(evt);
            }
        });

        jBDecBin.setBackground(new java.awt.Color(255, 255, 204));
        jBDecBin.setText("DB");
        jBDecBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDecBinActionPerformed(evt);
            }
        });

        jBOctBin.setBackground(new java.awt.Color(255, 255, 204));
        jBOctBin.setText("OB");
        jBOctBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOctBinActionPerformed(evt);
            }
        });

        jBOctHex.setBackground(new java.awt.Color(255, 255, 204));
        jBOctHex.setText("OH");
        jBOctHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOctHexActionPerformed(evt);
            }
        });

        jBHexOct.setBackground(new java.awt.Color(255, 255, 204));
        jBHexOct.setText("HO");
        jBHexOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHexOctActionPerformed(evt);
            }
        });

        jBDecHex.setBackground(new java.awt.Color(255, 255, 204));
        jBDecHex.setText("DH");
        jBDecHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDecHexActionPerformed(evt);
            }
        });

        jBDecOct.setBackground(new java.awt.Color(255, 255, 204));
        jBDecOct.setText("DO");
        jBDecOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDecOctActionPerformed(evt);
            }
        });

        jBHexDec.setBackground(new java.awt.Color(255, 255, 204));
        jBHexDec.setText("HD");
        jBHexDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHexDecActionPerformed(evt);
            }
        });

        jBHexBin.setBackground(new java.awt.Color(255, 255, 204));
        jBHexBin.setText("HB");
        jBHexBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHexBinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBDecBin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDecOct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDecHex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBOctDec, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBOctBin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBOctHex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBBinDec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBinOct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBinHex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBHexDec, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBHexBin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBHexOct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBSin)
                                            .addComponent(jB7)
                                            .addComponent(jB4)
                                            .addComponent(jB1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBCos)
                                            .addComponent(jB8)
                                            .addComponent(jB5)
                                            .addComponent(jB2)))
                                    .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBTan)
                                    .addComponent(jB9)
                                    .addComponent(jB6)
                                    .addComponent(jB3)
                                    .addComponent(jBPoint))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBDivision)
                                        .addComponent(jBOpposite))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBTimes)
                                        .addComponent(jBMinus)
                                        .addComponent(jBPlus)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBReverse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBCubeRoot)
                                    .addComponent(jBPower)
                                    .addComponent(jBAbsolute)
                                    .addComponent(jBLog)
                                    .addComponent(jBFactorial))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB1, jB2, jB3, jB4, jB5, jB6, jB7, jB8, jB9, jBAbsolute, jBBinDec, jBCos, jBCubeRoot, jBDivision, jBFactorial, jBLog, jBMinus, jBOpposite, jBPlus, jBPoint, jBPower, jBSin, jBTan, jBTimes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDecBin)
                    .addComponent(jBDecOct)
                    .addComponent(jBOctDec)
                    .addComponent(jBOctBin)
                    .addComponent(jBOctHex)
                    .addComponent(jBDecHex))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBinDec)
                    .addComponent(jBBinOct)
                    .addComponent(jBHexDec)
                    .addComponent(jBHexBin)
                    .addComponent(jBHexOct)
                    .addComponent(jBBinHex))
                .addGap(18, 18, 18)
                .addComponent(jBClear)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBOpposite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBDivision)
                            .addComponent(jBPercentage)
                            .addComponent(jBPower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBLog)
                            .addComponent(jBReverse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAbsolute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFactorial))
                    .addComponent(jBTan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB0))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBSquareRoot)
                        .addComponent(jBCubeRoot))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBCos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB8)
                            .addComponent(jB9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jB6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBPoint))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBTimes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBMinus)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBPlus))
                                            .addComponent(jBEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB0, jB1, jB2, jB3, jB4, jB5, jB6, jB7, jB8, jB9, jBAbsolute, jBBinDec, jBBinHex, jBBinOct, jBClear, jBCos, jBCubeRoot, jBDivision, jBLog, jBMinus, jBOctDec, jBOpposite, jBPercentage, jBPlus, jBPoint, jBPower, jBReverse, jBSin, jBSquareRoot, jBTan, jBTimes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClearActionPerformed
        jLDisplay.setText("");
    }//GEN-LAST:event_jBClearActionPerformed

    private void jBSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSinActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        calc.sin(r);        
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBSinActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"7");
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"4");
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"1");
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"0");
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCosActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        calc.cos(r);        
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBCosActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"8");
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"5");
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"2");
    }//GEN-LAST:event_jB2ActionPerformed

    private void jBBinDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBinDecActionPerformed
        Calculator calc = new Calculator();
        String s = jLDisplay.getText();
        calc.binDec(s);
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBBinDecActionPerformed

    private void jBTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTanActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        calc.tan(r);        
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBTanActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"9");
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"6");
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        jLDisplay.setText(jLDisplay.getText()+"3");
    }//GEN-LAST:event_jB3ActionPerformed

    private void jBPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPointActionPerformed
        jLDisplay.setText(jLDisplay.getText()+".");
    }//GEN-LAST:event_jBPointActionPerformed

    private void jBBinHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBinHexActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 2);
        calc.binHex(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBBinHexActionPerformed

    private void jBBinOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBinOctActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 2);
        calc.binOct(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBBinOctActionPerformed

    private void jBDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivisionActionPerformed
        jLDisplay.setText(jLDisplay.getText()+" / ");
    }//GEN-LAST:event_jBDivisionActionPerformed

    private void jBTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTimesActionPerformed
        jLDisplay.setText(jLDisplay.getText()+" * ");
    }//GEN-LAST:event_jBTimesActionPerformed

    private void jBMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMinusActionPerformed
        jLDisplay.setText(jLDisplay.getText()+" - ");
    }//GEN-LAST:event_jBMinusActionPerformed

    private void jBSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSquareRootActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        calc.squareRoot(r);
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBSquareRootActionPerformed

    private void jBPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPercentageActionPerformed
        jLDisplay.setText(jLDisplay.getText()+" %");
    }//GEN-LAST:event_jBPercentageActionPerformed

    private void jBReverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReverseActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        if (r != 0){
            calc.inverse(r);
            jLDisplay.setText(""+calc.getResult());
        } else {
            jLDisplay.setText("Error");
        }       
    }//GEN-LAST:event_jBReverseActionPerformed

    private void jBEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEqualsActionPerformed
        Calculator calc = new Calculator();
        String[] values = jLDisplay.getText().split(" ");      
        double value1 = Double.parseDouble(values[0]);
        double value2 = Double.parseDouble(values[2]);
        String operator = values[1];
        
        if (values.length == 4 && values[3].equals("%")){
                calc.percentage(value1, value2);
                value2 = calc.getPercent();
        }
        
        switch (operator){
            case "+":
                calc.plus(value1, value2);
                jLDisplay.setText(""+calc.getResult());
                break;
            case "-":
                calc.minus(value1, value2);
                jLDisplay.setText(""+calc.getResult());
                break;
            case "*":
                calc.times(value1, value2);
                jLDisplay.setText(""+calc.getResult());
                break;
            case "/":
                if (value2 == 0){
                    jLDisplay.setText("Error");
                } else {
                    calc.division(value1, value2);
                    jLDisplay.setText(""+calc.getResult());
                }                
                break;
            case "^":
                calc.power(value1, value2);
                jLDisplay.setText(""+calc.getResult());
                break;
            default:
                jLDisplay.setText("Error");
        }
        
    }//GEN-LAST:event_jBEqualsActionPerformed

    private void jBOppositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOppositeActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        if (r != 0){
            calc.opposite(r);        
            jLDisplay.setText(""+calc.getResult());
        } else {
            jLDisplay.setText("Error");
        }        
    }//GEN-LAST:event_jBOppositeActionPerformed

    private void jBPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlusActionPerformed
        jLDisplay.setText(jLDisplay.getText()+" + ");
    }//GEN-LAST:event_jBPlusActionPerformed

    private void jBOctDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOctDecActionPerformed
        Calculator calc = new Calculator();
        String s = jLDisplay.getText();
        calc.octDec(s);
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBOctDecActionPerformed

    private void jBCubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCubeRootActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        calc.cubeRoot(r);
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBCubeRootActionPerformed

    private void jBPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPowerActionPerformed
        jLDisplay.setText(jLDisplay.getText()+" ^ ");
    }//GEN-LAST:event_jBPowerActionPerformed

    private void jBAbsoluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbsoluteActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        calc.absolute(r);
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBAbsoluteActionPerformed

    private void jBLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        if (r > 0 || r < 0){
            calc.log(r);
            jLDisplay.setText(""+calc.getResult());
        } else {
            jLDisplay.setText("Error");
        }        
    }//GEN-LAST:event_jBLogActionPerformed

    private void jBFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFactorialActionPerformed
        Calculator calc = new Calculator();
        Double r = Double.parseDouble(jLDisplay.getText());
        if (r >= 0){
            calc.factorial(r);
            jLDisplay.setText(""+calc.getResult());
        } else {
            jLDisplay.setText("Error");
        }      
    }//GEN-LAST:event_jBFactorialActionPerformed

    private void jBDecBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDecBinActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 10);
        calc.decBin(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBDecBinActionPerformed

    private void jBOctBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOctBinActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 8);
        calc.octBin(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBOctBinActionPerformed

    private void jBOctHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOctHexActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 8);
        calc.octHex(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBOctHexActionPerformed

    private void jBHexOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHexOctActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 16);
        calc.hexOct(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBHexOctActionPerformed

    private void jBDecHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDecHexActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 10);
        calc.decHex(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBDecHexActionPerformed

    private void jBDecOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDecOctActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 10);
        calc.decOct(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBDecOctActionPerformed

    private void jBHexDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHexDecActionPerformed
        Calculator calc = new Calculator();
        String s = jLDisplay.getText();
        calc.hexDec(s);
        jLDisplay.setText(""+calc.getResult());
    }//GEN-LAST:event_jBHexDecActionPerformed

    private void jBHexBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHexBinActionPerformed
        Calculator calc = new Calculator();
        int c = Integer.parseInt(jLDisplay.getText(), 16);
        calc.hexBin(c);
        jLDisplay.setText(""+calc.getConversion());
    }//GEN-LAST:event_jBHexBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBAbsolute;
    private javax.swing.JButton jBBinDec;
    private javax.swing.JButton jBBinHex;
    private javax.swing.JButton jBBinOct;
    private javax.swing.JButton jBClear;
    private javax.swing.JButton jBCos;
    private javax.swing.JButton jBCubeRoot;
    private javax.swing.JButton jBDecBin;
    private javax.swing.JButton jBDecHex;
    private javax.swing.JButton jBDecOct;
    private javax.swing.JButton jBDivision;
    private javax.swing.JButton jBEquals;
    private javax.swing.JButton jBFactorial;
    private javax.swing.JButton jBHexBin;
    private javax.swing.JButton jBHexDec;
    private javax.swing.JButton jBHexOct;
    private javax.swing.JButton jBLog;
    private javax.swing.JButton jBMinus;
    private javax.swing.JButton jBOctBin;
    private javax.swing.JButton jBOctDec;
    private javax.swing.JButton jBOctHex;
    private javax.swing.JButton jBOpposite;
    private javax.swing.JButton jBPercentage;
    private javax.swing.JButton jBPlus;
    private javax.swing.JButton jBPoint;
    private javax.swing.JButton jBPower;
    private javax.swing.JButton jBReverse;
    private javax.swing.JButton jBSin;
    private javax.swing.JButton jBSquareRoot;
    private javax.swing.JButton jBTan;
    private javax.swing.JButton jBTimes;
    private javax.swing.JLabel jLDisplay;
    // End of variables declaration//GEN-END:variables
}
